import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const jobs = [
  {
    portal: 'LinkedIn',
    title: 'Senior Frontend Engineer',
    company: 'Razorpay',
    salary: '₹25L – ₹35L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'We are looking for a Senior Frontend Engineer to join our Payments team. You will build highly scalable, performant web applications using React and TypeScript. You will collaborate closely with design and backend teams to ship world-class financial products used by millions of merchants.',
    url: 'https://linkedin.com/jobs/1',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'Backend Engineer – Node.js',
    company: 'PhonePe',
    salary: '₹20L – ₹30L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Join PhonePe\'s core backend team to build and scale our payments infrastructure. You will design RESTful APIs, work with distributed systems, and ensure high availability. Experience with Node.js, PostgreSQL, and Redis is required.',
    url: 'https://naukri.com/jobs/1',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Indeed',
    title: 'Full Stack Developer',
    company: 'Swiggy',
    salary: '₹18L – ₹28L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Swiggy is hiring a Full Stack Developer to work on our consumer-facing web platforms. You will own end-to-end delivery of features from design to deployment. Strong proficiency in React, Node.js, and cloud infrastructure required.',
    url: 'https://indeed.com/jobs/1',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'React Native Developer',
    company: 'CRED',
    salary: '₹22L – ₹32L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'CRED is looking for a talented React Native developer to build delightful mobile experiences for our premium members. You will work on performance optimization, animations, and seamless integrations with backend services.',
    url: 'https://linkedin.com/jobs/2',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Wellfound',
    title: 'Full Stack Engineer (Remote)',
    company: 'Setu',
    salary: '₹16L – ₹24L/yr',
    location: 'Remote',
    jobType: 'Remote',
    description: 'Setu is a fintech infrastructure company building the pipes of India\'s financial system. We are looking for a Full Stack Engineer passionate about open banking. You will build developer-facing APIs and dashboards.',
    url: 'https://wellfound.com/jobs/1',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'DevOps Engineer',
    company: 'Flipkart',
    salary: '₹20L – ₹32L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'We are looking for a DevOps Engineer to join Flipkart\'s platform engineering team. You will manage CI/CD pipelines, Kubernetes clusters, and cloud infrastructure on AWS and GCP. Experience with Terraform, Helm, and monitoring tools required.',
    url: 'https://naukri.com/jobs/2',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Indeed',
    title: 'Data Scientist',
    company: 'Zomato',
    salary: '₹18L – ₹26L/yr',
    location: 'Gurugram',
    jobType: 'Full-time',
    description: 'Zomato\'s Data Science team is looking for a Data Scientist to work on recommendation systems and demand forecasting. You will build ML models using Python, TensorFlow, and deploy them at scale to improve restaurant discovery.',
    url: 'https://indeed.com/jobs/2',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'Product Manager – Growth',
    company: 'Meesho',
    salary: '₹30L – ₹45L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Meesho is hiring a Product Manager for our Growth team. You will own the end-to-end product roadmap for user acquisition and retention. You should have strong analytical skills, experience with A/B testing, and a deep understanding of e-commerce funnels.',
    url: 'https://linkedin.com/jobs/3',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Wellfound',
    title: 'Backend Engineer – Python',
    company: 'Darwinbox',
    salary: '₹14L – ₹20L/yr',
    location: 'Hyderabad',
    jobType: 'Full-time',
    description: 'Darwinbox is looking for a Backend Engineer to build the next generation of HR tech. You will design scalable APIs using Python and Django, work with PostgreSQL databases, and build integrations with third-party payroll systems.',
    url: 'https://wellfound.com/jobs/2',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Internshala',
    title: 'Frontend Developer Intern',
    company: 'Unacademy',
    salary: '₹25,000/month',
    location: 'Bangalore',
    jobType: 'Internship',
    description: 'Unacademy is offering a 6-month frontend development internship. You will work alongside senior engineers to build interactive learning experiences using React and TypeScript. This is a great opportunity to kickstart your career in edtech.',
    url: 'https://internshala.com/jobs/1',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'iOS Developer',
    company: 'Paytm',
    salary: '₹18L – ₹28L/yr',
    location: 'Noida',
    jobType: 'Full-time',
    description: 'Paytm is hiring an iOS Developer to build and enhance our flagship payments app used by 300M+ users. You will work with Swift, UIKit, and SwiftUI to build high-performance features and integrations with our payments SDK.',
    url: 'https://naukri.com/jobs/3',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'Senior Software Engineer – Go',
    company: 'Juspay',
    salary: '₹24L – ₹36L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Juspay builds payment orchestration infrastructure for the largest companies in the world. We are looking for a Senior Software Engineer proficient in Go to build highly concurrent, fault-tolerant payment routing systems.',
    url: 'https://linkedin.com/jobs/4',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Wellfound',
    title: 'UI/UX Designer (Remote)',
    company: 'Groww',
    salary: '₹12L – ₹18L/yr',
    location: 'Remote',
    jobType: 'Remote',
    description: 'Groww is hiring a UI/UX Designer to craft beautiful and intuitive investment experiences. You will own design end-to-end, from research and wireframes to high-fidelity prototypes. Proficiency in Figma and a strong portfolio required.',
    url: 'https://wellfound.com/jobs/3',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Indeed',
    title: 'Android Developer',
    company: 'MakeMyTrip',
    salary: '₹16L – ₹25L/yr',
    location: 'Gurugram',
    jobType: 'Full-time',
    description: 'MakeMyTrip is seeking a skilled Android Developer to work on our travel booking app with 75M+ downloads. You will build new features using Kotlin and Jetpack Compose, optimize for performance, and integrate with our backend APIs.',
    url: 'https://indeed.com/jobs/3',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'Machine Learning Engineer',
    company: 'Ola',
    salary: '₹22L – ₹35L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Ola\'s AI team is looking for a Machine Learning Engineer to build dynamic pricing and ETA prediction models. You will work with large-scale geospatial data, design feature pipelines, and deploy ML models to production using Python and PyTorch.',
    url: 'https://naukri.com/jobs/4',
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'Software Development Engineer II',
    company: 'Amazon India',
    salary: '₹35L – ₹55L/yr',
    location: 'Hyderabad',
    jobType: 'Full-time',
    description: 'Amazon is hiring an SDE II for our Supply Chain team. You will design and build distributed systems that power Amazon\'s fulfillment network. Strong Java or Kotlin background, system design skills, and experience with AWS services required.',
    url: 'https://linkedin.com/jobs/5',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Internshala',
    title: 'Backend Development Intern',
    company: 'Postman',
    salary: '₹30,000/month',
    location: 'Bangalore',
    jobType: 'Internship',
    description: 'Join Postman as a Backend Development Intern and work on the tools that 25M+ developers use daily. You will build features in Node.js, contribute to our API platform, and get mentored by world-class engineers.',
    url: 'https://internshala.com/jobs/2',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Wellfound',
    title: 'Staff Engineer – Platform',
    company: 'BrowserStack',
    salary: '₹45L – ₹65L/yr',
    location: 'Mumbai',
    jobType: 'Full-time',
    description: 'BrowserStack is hiring a Staff Engineer to lead our Platform team. You will architect scalable infrastructure, mentor engineers, and define technical direction. Experience with distributed systems, cloud architecture, and leading cross-functional teams required.',
    url: 'https://wellfound.com/jobs/4',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Indeed',
    title: 'Cloud Architect (Remote)',
    company: 'Freshworks',
    salary: '₹40L – ₹60L/yr',
    location: 'Remote',
    jobType: 'Remote',
    description: 'Freshworks is looking for a Cloud Architect to design and optimize multi-cloud infrastructure across AWS, GCP, and Azure. You will drive cloud strategy, define architecture standards, and work closely with engineering teams to ensure scalability and reliability.',
    url: 'https://indeed.com/jobs/4',
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'Engineering Manager',
    company: 'Zepto',
    salary: '₹50L – ₹75L/yr',
    location: 'Mumbai',
    jobType: 'Full-time',
    description: 'Zepto is hiring an Engineering Manager to lead our Delivery Experience team. You will manage a team of 8 engineers, drive technical roadmap, and collaborate with product and design to build features that delight customers. Prior hands-on engineering experience required.',
    url: 'https://linkedin.com/jobs/6',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'Java Developer',
    company: 'Infosys',
    salary: '₹8L – ₹14L/yr',
    location: 'Pune',
    jobType: 'Full-time',
    description: 'Infosys is looking for Java Developers to work on enterprise application development for our global clients. You will build microservices using Spring Boot, work with relational databases, and participate in Agile delivery processes.',
    url: 'https://naukri.com/jobs/5',
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Internshala',
    title: 'Data Science Intern',
    company: 'Fractal Analytics',
    salary: '₹20,000/month',
    location: 'Mumbai',
    jobType: 'Internship',
    description: 'Fractal Analytics is offering a Data Science internship for final-year students. You will work on real client data, build predictive models using Python and scikit-learn, and present insights to business stakeholders. Prior ML project experience preferred.',
    url: 'https://internshala.com/jobs/3',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'LinkedIn',
    title: 'Site Reliability Engineer',
    company: 'Atlassian',
    salary: '₹28L – ₹42L/yr',
    location: 'Bangalore',
    jobType: 'Hybrid',
    description: 'Atlassian is hiring an SRE to ensure the reliability and scalability of Jira and Confluence. You will own observability, define SLOs, automate incident response, and work with engineering teams to build more reliable services. Experience with Kubernetes, Prometheus, and PagerDuty preferred.',
    url: 'https://linkedin.com/jobs/7',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Wellfound',
    title: 'Technical Lead – Fintech',
    company: 'Slice',
    salary: '₹30L – ₹45L/yr',
    location: 'Bangalore',
    jobType: 'Full-time',
    description: 'Slice is looking for a Technical Lead to own the architecture and delivery of our credit card platform. You will lead a team of 5 engineers, make architectural decisions, and collaborate with product leadership. Strong Node.js and system design skills required.',
    url: 'https://wellfound.com/jobs/5',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Indeed',
    title: 'Contract – React Developer',
    company: 'Wipro Technologies',
    salary: '₹60 – ₹80/hr',
    location: 'Chennai',
    jobType: 'Contract',
    description: 'Wipro is looking for a contract React Developer for a 6-month engagement with a leading BFSI client. You will build complex dashboard components, integrate with REST APIs, and work in an Agile team. Strong React and TypeScript skills required.',
    url: 'https://indeed.com/jobs/5',
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    portal: 'Naukri',
    title: 'Senior Data Engineer',
    company: 'Dream11',
    salary: '₹24L – ₹36L/yr',
    location: 'Mumbai',
    jobType: 'Full-time',
    description: 'Dream11 is hiring a Senior Data Engineer to build and maintain our real-time data platform. You will work with Apache Kafka, Apache Spark, and dbt to process billions of events during live matches. Experience with data warehousing and cloud data platforms (BigQuery, Snowflake) required.',
    url: 'https://naukri.com/jobs/6',
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing jobs
  await prisma.savedJob.deleteMany();
  await prisma.application.deleteMany();
  await prisma.job.deleteMany();

  for (const job of jobs) {
    await prisma.job.create({ data: job });
  }

  console.log(`✅ Seeded ${jobs.length} jobs successfully`);
}

main()
  .catch(e => { console.error('Seed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
